//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegForm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserId { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage ="This field is required !")]
        public string Username { get; set; }

        [Required(ErrorMessage = "This field is required !")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "This field is required !")]
        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [DisplayName("IsAdmin")]
        public bool isAdmin { get; set; }

        [Required(ErrorMessage = "This field is required !")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This field is required !")]
        [DataType(DataType.Date)]
        [DisplayName("Date of Birth")]
        public System.DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "This field is required !")]
        public string Email { get; set; }

        [Required(ErrorMessage = "This field is required !")]
        public string Phone { get; set; }
    }
}
